---
## VARS
# vm_utils_terraform_provider - Sets the provider to be used in the terraform_vms play and inventory file. Default: "libvirt"
# vm_utils_terraform_env - Sets the environment to be used in the terraform_vms play and inventory file. Default: "dev"
# vm_utils_terraform_project_path - Sets the path to the terraform project to be used in the terraform_vms play. Default:
#   "{{ lookup('env', 'PWD') + '/terraform' + terraform_env + '/' + terraform_provider + '/' }}"
# vm_utils_terraform_workspace - Sets the workspace to be used in the terraform_vms play and inventory file. Default:
#   "{{ terraform_provider + '-' + terraform_env }}"
# vm_utils_terraform_inventory_path - Sets the path to the inventory file to be used in the terraform_vms play. Default:
#   "{{ lookup('env', 'PWD') + '/inventories/' + terraform_env + '/terraform.yml' }}"
# vm_utils_terraform_inventory_name - Sets the name of the inventory file to be used in the terraform_vms play. Default: env
##
## SHORTCUTS (takes precedence over vm_utils_terraform_*)
# env - vm_utils_terraform_env
# provider - vm_utils_terraform_provider
# workspace - vm_utils_terraform_workspace
##

- name: "Terraform | Deployment"
  hosts: localhost
  gather_facts: false
  vars:
    # ENVIRONMENT
    # Defaults to demo
    # Can be overwritten with vm_utils_terraform_env or env
    _vm_utils_terraform_env: "{{ env | default(_env) }}"
    _env: "{{ vm_utils_terraform_env | default('demo') }}"
    # INVENTORY NAME
    # Defaults to env, e.g. dev
    # Can be overwritten with vm_utils_terraform_inventory_name or inventory_name
    _vm_utils_terraform_inventory_name: "{{ vm_utils_terraform_inventory_name | default(_vm_utils_terraform_env) }}"
    # INVENTORY PATH
    # Defaults to ${PWD}/inventories/env/terraform.yml, e.g. ./inventories/dev/terraform.yml
    # Can be overwritten with vm_utils_terraform_inventory_path
    _vm_utils_terraform_inventory_path: "{{ vm_utils_terraform_inventory_path | default(lookup('env', 'PWD') + '/inventories/' +
      _vm_utils_terraform_inventory_name + '/terraform.yml') }}"
    # PROJECT PATH
    # Defaults to ${PWD}/terraform/infra/provider/, e.g. ./terraform/infra/libvirt/
    # Can be overwritten with vm_utils_terraform_project_path
    _vm_utils_terraform_project_path: "{{ vm_utils_terraform_project_path | default(_project_path) }}"
    _project_path: "{{ lookup('env', 'PWD') + '/terraform/infra/' + _vm_utils_terraform_provider + '/' }}"
    # PROVIDER
    # Defaults to libvirt
    # Can be overwritten with vm_utils_terraform_provider or provider
    _vm_utils_terraform_provider: "{{ provider | default(_provider) }}"
    _provider: "{{ vm_utils_terraform_provider | default('libvirt') }}"
    # WORKSPACE
    # Defaults to provider-env, e.g. libvirt-dev
    # Can be overwritten with vm_utils_terraform_workspace or workspace
    _vm_utils_terraform_workspace: "{{ workspace | default(_workspace) }}"
    _workspace: "{{ vm_utils_terraform_workspace | default(_vm_utils_terraform_provider + '-' + _vm_utils_terraform_env) }}"
  tasks:
    - name: "Replace terraform_path in inventory file"
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'PWD') + '/inventories/' + _vm_utils_terraform_inventory_name + '/terraform.yml' }}"  # noqa: jinja[spacing]
        regexp: '^project_path:'
        line: "project_path: \"{{ _vm_utils_terraform_project_path | regex_replace(lookup('env', 'PWD'), '.') }}\""  # Make it a relative path
      delegate_to: localhost
      when:
        - _vm_utils_terraform_project_path is defined
        - _vm_utils_terraform_inventory_name is defined

    - name: "Replace workspace in inventory file"
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'PWD') + '/inventories/' + _vm_utils_terraform_inventory_name + '/terraform.yml' }}"  # noqa: jinja[spacing]
        regexp: '^workspace:'
        line: "workspace: \"{{ _vm_utils_terraform_workspace }}\""  # Make it a relative path
      delegate_to: localhost
      when:
        - _vm_utils_terraform_project_path is defined
        - _vm_utils_terraform_inventory_name is defined
        - _vm_utils_terraform_workspace is defined
...
