---
## VARS
# vm_utils_terraform_provider - Sets the provider to be used in the terraform_vms play and inventory file. Default: "libvirt"
# vm_utils_terraform_env - Sets the environment to be used in the terraform_vms play and inventory file. Default: "dev"
# vm_utils_terraform_project_path - Sets the path to the terraform project to be used in the terraform_vms play. Default:
#   "{{ lookup('env', 'PWD') + '/terraform' + terraform_env + '/' + terraform_provider + '/' }}"
##
## SHORTCUTS
# env - Sets the environment to be used in the terraform_vms play and inventory file. Default: "dev"
# provider - Sets the provider to be used in the terraform_vms play and inventory file. Default: "libvirt"
##

- name: "Terraform | Deployment"
  hosts: localhost
  gather_facts: false
  vars:
    __vm_utils_terraform_provider: "{{ vm_utils_terraform_provider | default(_provider) }}"
    _provider: "{{ provider | default('libvirt') }}"
    __vm_utils_terraform_env: "{{ vm_utils_terraform_env | default(_env) }}"
    _env: "{{ env | default('dev') }}"
    __vm_utils_terraform_project_path: "{{ vm_utils_terraform_project_path | default(_project_path) }}"
    _project_path: "{{ lookup('env', 'PWD') + '/terraform/infra/' + __vm_utils_terraform_env + '/' + __vm_utils_terraform_provider + '/' }}"
  tasks:
    - name: Set _vm_utils_terraform_project_path
      ansible.builtin.set_fact:
        _vm_utils_terraform_project_path: "{{ __vm_utils_terraform_project_path }}"

    - name: Set _vm_utils_terraform_env
      ansible.builtin.set_fact:
        _vm_utils_terraform_env: "{{ __vm_utils_terraform_env }}"

    - name: Set _vm_utils_terraform_provider
      ansible.builtin.set_fact:
        _vm_utils_terraform_provider: "{{ __vm_utils_terraform_provider }}"

    - name: "Replace terraform_path in inventory file"
      ansible.builtin.lineinfile:
        path: "{{ lookup('env', 'PWD') + '/inventories/' + _vm_utils_terraform_env + '/terraform.yml' }}"  # noqa: jinja[spacing]
        regexp: '^project_path:'
        line: "project_path: \"{{ _vm_utils_terraform_project_path | regex_replace(lookup('env', 'PWD'), '.') }}\""  # Make it a relative path
      delegate_to: localhost
      when:
        - _vm_utils_terraform_provider is defined
        - _vm_utils_terraform_env is defined

...
